<?php

    // php carriers object for matching value to actual option name 
    $carriers = [
        'sms_carriers__us__alltel' => 'Alltel',
            'sms_carriers__us__alaska_communications' => 'Alaska Communications',
            'sms_carriers__us__assurance_wireless' => 'Assurance Wireless',
            'sms_carriers__us__at_and_t' => 'AT&T Wireless',
            'sms_carriers__us__bluegrass' => 'Bluegrass Cellular',
            'sms_carriers__us__bluesky' => 'Bluesky Communications',
            'sms_carriers__us__blueskyfrog' => 'BlueSkyFrog',
            'sms_carriers__us__boostmobile' => 'Boost Mobile',
            'sms_carriers__us__cellcom' => 'Cellcom',
            'sms_carriers__us__cellularsouth' => 'Cellular South',
            'sms_carriers__us__centennial_wireless' => 'Centennial Wireless',
            'sms_carriers__us__chariton_valley' => 'Chariton Valley Wireless',
            'sms_carriers__us__chat_mobility' => 'Chat Mobility',
            'sms_carriers__us__cincinnati_bell' => 'Cincinnati Bell',
            'sms_carriers__us__cingular' => 'Cingular (Postpaid)',
            'sms_carriers__us__cleartalk' => 'Cleartalk Wireless',
            'sms_carriers__us__comcast_pcs' => 'Comcast PCS',
            'sms_carriers__us__cricket' => 'Cricket',
            'sms_carriers__us__cspire' => 'C Spire Wireless',
            'sms_carriers__us__dtc_wireless' => 'DTC Wireless',
            'sms_carriers__us__element' => 'Element Mobile',
            'sms_carriers__us__esendex' => 'Esendex',
            'sms_carriers__us__general_comm' => 'General Communications Inc.',
            'sms_carriers__us__golden_state' => 'Golden State Cellular',
            'sms_carriers__us__google_voice' => 'Google Voice',
            'sms_carriers__us__greatcall' => 'GreatCall',
            'sms_carriers__us__helio' => 'Helio',
            'sms_carriers__us__kajeet' => 'Kajeet',
            'sms_carriers__us__longlines' => 'LongLines',
            'sms_carriers__us__metro_pcs' => 'Metro PCS',
            'sms_carriers__us__nextech' => 'Nextech',
            'sms_carriers__us__pioneer' => 'Pioneer Cellular',
            'sms_carriers__us__psc_wireless' => 'PSC Wireless',
            'sms_carriers__us__rogers_wireless' => 'Rogers Wireless',
            'sms_carriers__us__qwest' => 'Qwest',
            'sms_carriers__us__simple_mobile' => 'Simple Mobile',
            'sms_carriers__us__solavei' => 'Solavei',
            'sms_carriers__us__south_central' => 'South Central Communications',
            'sms_carriers__us__southernlink' => 'Southern Link',
            'sms_carriers__us__sprint' => 'Sprint PCS',
            'sms_carriers__us__straight_talk' => 'Straight Talk',
            'sms_carriers__us__syringa' => 'Syringa Wireless',
            'sms_carriers__us__t_mobile' => 'T-Mobile',
            'sms_carriers__us__teleflip' => 'Teleflip',
            'sms_carriers__us__ting' => 'Ting',
            'sms_carriers__us__tracfone' => 'Tracfone',
            'sms_carriers__us__telus_mobility' => 'Telus Mobility',
            'sms_carriers__us__unicel' => 'Unicel',
            'sms_carriers__us__us_cellular' => 'US Cellular',
            'sms_carriers__us__usa_mobility' => 'USA Mobility',
            'sms_carriers__us__verizon_wireless' => 'Verizon Wireless',
            'sms_carriers__us__viaero' => 'Viaero',
            'sms_carriers__us__virgin_mobile' => 'Virgin Mobile',
            'sms_carriers__us__voyager_mobile' => 'Voyager Mobile',
            'sms_carriers__us__west_central' => 'West Central Wireless',
            'sms_carriers__us__xit_comm' => 'XIT Communications'
    ];

    ?>