var carriers = {
            'Alltel': 'alltel',
            'Alaska Communications': 'alaska_communications',
            'Assurance Wireless': 'assurance_wireless',
            'AT&T Wireless': 'at_and_t',
            'Bluegrass Cellular': 'bluegrass',
            'Bluesky Communications': 'bluesky',
            'BlueSkyFrog': 'blueskyfrog',
            'Boost Mobile': 'boostmobile',
            'Cellcom': 'cellcom',
            'Cellular South': 'cellularsouth',
            'Centennial Wireless': 'centennial_wireless',
            'Chariton Valley Wireless': 'chariton_valley',
            'Chat Mobility': 'chat_mobility',
            'Cincinnati Bell': 'cincinnati_bell',
            'Cingular (Postpaid)': 'cingular',
            'Cleartalk Wireless': 'cleartalk',
            'Comcast PCS': 'comcast_pcs',
            'Cricket': 'cricket',
            'C Spire Wireless': 'cspire',
            'DTC Wireless': 'dtc_wireless',
            'Element Mobile': 'element',
            'Esendex': 'esendex',
            'General Communications Inc.': 'general_comm',
            'Golden State Cellular': 'golden_state',
            'Google Voice': 'google_voice',
            'GreatCall': 'greatcall',
            'Helio': 'helio',
            'Kajeet': 'kajeet',
            'LongLines': 'longlines',
            'Metro PCS': 'metro_pcs',
            'Nextech': 'nextech',
            'Pioneer Cellular': 'pioneer',
            'PSC Wireless': 'psc_wireless',
            'Rogers Wireless': 'rogers_wireless',
            'Qwest': 'qwest',
            'Simple Mobile': 'simple_mobile',
            'Solavei': 'solavei',
            'South Central Communications': 'south_central',
            'Southern Link': 'southernlink',
            'Sprint PCS': 'sprint',
            'Straight Talk': 'straight_talk',
            'Syringa Wireless': 'syringa',
            'T-Mobile': 't_mobile',
            'Teleflip': 'teleflip',
            'Ting': 'ting',
            'Tracfone': 'tracfone',
            'Telus Mobility': 'telus_mobility',
            'Unicel': 'unicel',
            'US Cellular': 'us_cellular',
            'USA Mobility': 'usa_mobility',
            'Verizon Wireless': 'verizon_wireless',
            'Viaero': 'viaero',
            'Virgin Mobile': 'virgin_mobile',
            'Voyager Mobile': 'voyager_mobile',
            'West Central Wireless': 'west_central',
            'XIT Communications': 'xit_comm'
}